### ISSUE TITLE
crashing when clicking on the icon

### ISSUE THREAD

**Issue by notpyrozn** [Weebifying/separate-dual-icons-geode#19]
idk why this is happening, but when i click on the p2 icon the game crashes

https://github.com/user-attachments/assets/bc31b6ab-9bfe-4f08-ba6f-08a10bddc8c2

![image](https://github.com/user-attachments/assets/c110c6ed-8a4b-4254-9bc2-5ee80874c22c)

2024-09-11T13:07:58-0300
Whoopsies! An unhandled exception has occurred.
It appears that the crash occurred while executing code from the "weebify.separate_dual_icons" mod. Please submit this crash report to its developers (Weebify) for assistance.

== Geode Information ==
Loader Version: v3.5.0
Loader Commit: ebd65ca
Bindings Commit: bd13cd0
Installed mods: 72
Problems: 7

== Exception Information ==
Faulty Module: C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\geode\unzipped\weebify.separate_dual_icons\weebify.separate_dual_icons.dll
Faulty Mod: Separate Dual Icons v1.2.2 (weebify.separate_dual_icons)
Exception Code: c0000005 (EXCEPTION_ACCESS_VIOLATION)
Exception Flags: 0
Exception Address: 00007FFD4D525F08 (weebify.separate_dual_icons.dll + 15f08)
Number Parameters: 2
Crashed thread: Main

== Stack Trace ==
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\geode\unzipped\weebify.separate_dual_icons\weebify.separate_dual_icons.dll + 15f08
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + 597cf (cocos2d::CCMenuItem::activate + 47)
 - 000001BA9F020872 (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\Geode.dll + 3c0a5 (geode::modifier::AsStaticFunction_activate<hook7<(anonymous namespace)::hook7Parent>,void (hook7<(anonymous namespace)::hook7Parent>::*)()>::Impl<void (hook7<(anonymous namespace)::hook7Parent>::*)()>::function + 21 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenuItem.hpp:35)
 - 000001BA9F020872 (Hook handler)
 - 000001BA9F75BC72 (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\geode\unzipped\alphalaneous.happy_textures\alphalaneous.happy_textures.dll + 7f0c1
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\geode\unzipped\alphalaneous.happy_textures\alphalaneous.happy_textures.dll + 5412c
 - 000001BA9F75BC72 (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + 58798 (cocos2d::CCMenu::ccTouchEnded + 40)
 - 000001BA9F020C72 (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\Geode.dll + 3c76f (geode::modifier::AsStaticFunction_ccTouchEnded<hook15<(anonymous namespace)::hook15Parent>,void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::Impl<void (hook15<(anonymous namespace)::hook15Parent>::*)(cocos2d::CCTouch *, cocos2d::CCEvent *)>::function + 47 | /home/runner/work/geode/geode/build/bindings/bindings/Geode/modify/CCMenu.hpp:105)
 - 000001BA9F020C72 (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + b0c3c (cocos2d::CCTouchDispatcher::touches + 444)
 - 000001BA9F7D6072 (Hook handler)
 - 000001BA9F7D6072 (Hook handler)
 - 000001BA9F7D6072 (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + 6b131 (cocos2d::CCEGLViewProtocol::handleTouchesEnd + 97)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + 76159 (cocos2d::CCEGLView::onGLFWMouseCallBack + 249)
 - 000001BA9F81D47B (Hook handler)
 - 000001BA9F81D47B (Hook handler)
 - 000001BA9F81D47B (Hook handler)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + 76186
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + d686b
 - C:\Windows\System32\USER32.dll + ef5c
 - C:\Windows\System32\USER32.dll + e9de (CallWindowProcW + 142)
 - C:\Windows\SYSTEM32\OPENGL32.dll + 3f1f0
 - C:\Windows\System32\USER32.dll + ef5c
 - C:\Windows\System32\USER32.dll + e684
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + d4198
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\libcocos2d.dll + 72ca6 (cocos2d::CCApplication::run + 1078)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\GeometryDash.exe + 4a2d69
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\Geode.dll + 24aaca (gdMainHook + 554 | /home/runner/work/geode/geode/loader/src/platform/windows/main.cpp:167)
 - C:\Users\lucas\Downloads\Geometry.Dash. 2.206 PC\GeometryDash.exe + 4a415a
 - C:\Windows\System32\KERNEL32.DLL + 17374 (BaseThreadInitThunk + 20)
 - C:\Windows\SYSTEM32\ntdll.dll + 4cc91 (RtlUserThreadStart + 33)

== Register States ==
RAX: 0000000000000000
RBX: 0000000000000000
RCX: 000001baa812b510
RDX: 000001ba9d3b0aa0
RBP: 0000000000000000
RSP: 000000aa7e8ff920
RDI: 0000000000000000
RSI: 0000000000000000
RIP: 00007ffd8df7cc91
R8:  0000000000000001
R9:  000001baa7d96da0
R10: 0000000000000001
R11: 000000aa7e8fd820
R12: 0000000000000000
R13: 0000000000000000
R14: 0000000000000000
R15: 0000000000000000

== Installed Mods ==
x | [v1.0.3] alphalaneous.awesome_modifier_icons
x | [v1.0.0-beta.3] alphalaneous.editortab_api
x | [v1.4.10] alphalaneous.happy_textures
x | [v1.2.9] alphalaneous.pages_api
x | [v1.2.10] alphalaneous.projectedstars
x | [v1.1.11] b1rtek.gddlintegration
x | [v1.8.3] beat.click-sound
x | [v1.1.0] capeling.coloured-wave-trail
x | [v1.0.2] capeling.hide_main_menu_ui
! | [v1.1.4] capeling.icon_profile_2.2
x | [v1.0.7] cdc.level_thumbnails
  | [v2.0.0] crewly.comboburst
x | [v4.2.8] cvolton.betterinfo
x | [v1.0.1] cvolton.level-id-api
x | [v1.2.1] cvolton.misc_bugfixes
x | [v1.6.2] dankmeme.globed2
x | [v1.3.3-alpha.2] elnexreal.copy_song_id
x | [v2.1.2] elohmrow.death_tracker
! | [v1.3.1] elsai.a_daily_shop
x | [v1.0.1] fig.authentication
x | [v1.0.9] firee.goldenbest
x | [v1.1.3] firee.object-workshop
x | [v0.3.2] flafy.autonong
x | [v2.11.0] fleym.nongd
x | [v1.3.9] gdutilsdevs.gdutils
x | [v1.7.1] geode.custom-keybinds
x | [v3.5.0] geode.loader
x | [v1.13.2] geode.node-ids
x | [v1.6.1] geode.texture-loader
x | [v1.4.8] hiimjustin000.fake_rate
x | [v1.1.0] hjfod.backups
x | [v6.7.0] hjfod.betteredit
x | [v1.3.0] hjfod.gdshare
x | [v1.2.1] hjfod.gmd-api
x | [v1.0.0] hjfod.trashcan
x | [v1.1.1] iliashdz.jesus
x | [v1.2.1] itzkiba.better_progression
x | [v1.2.0] itzkiba.grandpa_demon
x | [v1.2.0] jojo989.main_menu_bg_customizer
x | [v1.0.7] jouca.badgesapi
x | [v1.2.0] khronophobia.inputs_viewer
x | [v1.1.1] lynxdeer.autodeafen
x | [v1.0.4] mat.max-window
x | [v1.2.1] mat.run-info
x | [v1.2.0] mat.scroll-zoom
x | [v1.1.0] mat.song-preview
! | [v2.11.1] maxnu.gd_mega_overlay
x | [v2.1.1] naxrin.rgb_icons
  | [v1.1.4] ninkaz.blending_glow
  | [v1.1.2] ninxout.redash
x | [v1.4.0-beta.2] oatmealine.ids_integration
x | [v1.4.0-beta.3] oatmealine.nlw_integration
x | [v1.2.1] omgrod.geodify
! | [v2.2.2] prevter.openhack
x | [v1.4.1] raydeeux.loadingscreentweaks
x | [v1.2.2] shineua.geometrize2gd
x | [v2.1.0] spaghettdev.gd-roulette
  | [v1.1.21] syzzi.click_between_frames
x | [v2.12.2] techstudent10.discord_rich_presence
! | [v1.1.0] thesillydoggo.better_startpos_menu
  | [v1.1.0] thesillydoggo.comment_emojis
x | [v1.0.4] thesillydoggo.icon_kit_switcher
x | [v1.6.4] thesillydoggo.qolmod
! | [v1.6.8] tpdea.betterpause-Better
x | [v1.12.7] undefined0.gdtweaks
x | [v1.3.3] uproxide.textures
x | [v1.0.4] weebify.congregation_jumpscare
x | [v1.2.2] weebify.separate_dual_icons
x | [v1.0.1] xanii.super_expert
x | [v1.1.0] xanii.youtubers
  | [v0.9.7] zalphalaneous.minecraft
~ | [v2.0.0-alpha.5] zilko.xdbot

**Comment by notpyrozn** [comment]
i downgraded to the version before and now it works

**Comment by Weebifying** [comment]
fixed in 1.2.3

**Comment by notpyrozn** [comment]
nice
