### ISSUE TITLE
Compatibility with another mod

### ISSUE THREAD

**Issue by Sushi8756** [Weebifying/separate-dual-icons-geode#2]
Please make this compatible with Custom Gamemode Colors by Rooot please that would lead to so much more options for icons 🙏🙏

![Screenshot_20240310_174022_One UI Home](https://github.com/Weebifying/separate-dual-icons-geode/assets/90991195/c5c0fa92-bfc8-486b-b83e-ecc049e54b8e)
(Not really an issue but idk where else to ask sorry)

**Comment by Weebifying** [comment]
no thanks

**Comment by Sushi8756** [comment]
> no thanks

Lmao okay makes sense
