### ISSUE TITLE
Suggestion about the p1 and p2 colors at levels

### ISSUE THREAD

**Issue by Lizardking1123** [Weebifying/separate-dual-icons-geode#7]
Can you customize the p1 and p2 colors at levels that you can choose either of those colors from either player 1 or 2?

**Comment by Hanifinio** [comment]
What are you trying to say?

**Comment by Hanifinio** [comment]
Oh that sounds really cool. Hopefully we get it!

**Comment by Hanifinio** [comment]
Awh that sucks. It is very far from needed tho
